# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 399)
        self.roast = QtWidgets.QComboBox(Dialog)
        self.roast.setGeometry(QtCore.QRect(167, 50, 251, 31))
        self.roast.setObjectName("roast")
        self.volume = QtWidgets.QSpinBox(Dialog)
        self.volume.setGeometry(QtCore.QRect(377, 170, 44, 31))
        self.volume.setMinimum(1)
        self.volume.setMaximum(10000)
        self.volume.setObjectName("volume")
        self.taste = QtWidgets.QTextEdit(Dialog)
        self.taste.setGeometry(QtCore.QRect(170, 210, 251, 141))
        self.taste.setObjectName("taste")
        self.price = QtWidgets.QSpinBox(Dialog)
        self.price.setGeometry(QtCore.QRect(377, 130, 44, 31))
        self.price.setMinimum(1)
        self.price.setMaximum(10000)
        self.price.setObjectName("price")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(12, 360, 411, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 111, 31))
        self.label_6.setObjectName("label_6")
        self.sort = QtWidgets.QLineEdit(Dialog)
        self.sort.setGeometry(QtCore.QRect(167, 10, 251, 31))
        self.sort.setObjectName("sort")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.label.setObjectName("label")
        self.grind = QtWidgets.QComboBox(Dialog)
        self.grind.setGeometry(QtCore.QRect(167, 90, 251, 31))
        self.grind.setToolTipDuration(-4)
        self.grind.setObjectName("grind")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Ок"))
        self.label_6.setText(_translate("Dialog", "Описание вкуса"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_4.setText(_translate("Dialog", "Цена"))
        self.label_3.setText(_translate("Dialog", "Помол"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_5.setText(_translate("Dialog", "Объем упаковки"))
